config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :boards, shallow: true do
    resources :cards do
      collection do
        get :get_children
      end
      resources :tasks
    end
    get 'tasks/change', to: 'tasks#change'

  end

  resources :users, only: [:index, :show, :edit] do 
    collection do
      post :add
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :home, only: [:new, :index]

  get '/logout', to: 'home#logout', as: 'logout'

  resources :organisations do
  	  collection do
    	get 'plan_choice'
    	patch 'subscribed'
      get 'alter'
  	  end
  end


  resources :subscriptions do
  	collection do 
  		get :details
      get :calculate
    end
  end


  namespace :api do
    namespace :v1 do
      resources :users
      resources :projects
      # resources :projects, only: [:index] do
      #   collection do
      #     get 'import'
      #   end
      # end
    end
  end

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :board

  belongs_to :parent, :class_name => "Card", :foreign_key => "parent_id", optional: true
  has_many :children, :class_name => "Card", :foreign_key => "parent_id"
  has_many :tasks, dependent: :destroy
  validates_length_of :title,  maximum: 288, presence: true

  def completed
    tasks.where(completed: true).blank?
  end

  def self.competed_cards
    self.distinct.joins(:tasks).where("tasks.completed = true")
  end

  def self.uncompleted_cards 
  	self.distinct.joins(:tasks).where("tasks.completed = false")
  end


end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_board, only: [ :edit, :update, :index, :new, :create, :get_children]
  before_action :set_card, only: [:show, :destroy]
  before_action :authenticate_board, only: [:show, :edit, :destroy, :index]

  def index
    @cards = @board.cards.where(parent_id: '')
    @completed_cards = @board.cards.competed_cards
    @uncompleted_cards = @board.cards.uncompleted_cards
  end

  def new
    @cards = @board.cards.collect {|s| [s.title, s.id]}
    @card = Card.new

  end

  def create
    params[:card][:created_by] = current_user.id
    @card = @board.cards.new(card_params)

    respond_to do |format|
      if @card.save
          format.html {redirect_to board_cards_url , notice: 'Card was successfully created.' }
        else
          format.html { render :new }
        end
    end     
  end

  def edit
  end

  def update
  end

  def destroy
    unless @card.tasks.size > 0 || @card.children.size > 0
      @card.destroy
      notice = "Card was successfully deleted"
    else
      notice = "The card have some dependencies, it may child cards or tasks"
    end
    respond_to do |format|
        format.html {redirect_to board_cards_url(@board) , notice: notice }
    end 
  end

  def get_children
    @parent = Card.find(params[:parent])
    @children = @parent.children
  end

  def show
    @tasks = @card.tasks
  end

private 

    def card_params
      params.require(:card).permit( :title, :description, :parent_id, :created_by, :board_id)
    end

    def set_board
      @board = Board.find(params[:board_id])
    end

    def set_card
      @card = Card.find(params[:id])
      @board = @card.board
    end

end

app/helpers/cards_helper.rb
module CardsHelper

  def border_color card
    if card.tasks.blank?
      return "#0000FF"
    elsif card.completed
      return "#3CFF33"
    else
      return "#FF3333" 
    end
  end

end

app/views/cards/_card.html.erb
    
    <% unless @children.blank? %>
      <div class="link"></div>
      <%end%>
  		<% @children.each do |card| %>
        <div class="row" style="margin-bottom: 5px;padding-left: 30px;">
        <div class="col-sm-2 card-1" style="border-color: <%=border_color(card)%>" onclick="card_tasks('<%=card.id%>')" id="card_<%=card.id%>">
          <%=card.title%>  
        </div>

        <!-- Modal -->
        <div class="tasks_modal" id="Modal_<%=card.id%>" >
        </div>

        <div class="col" id="parent_<%=card.id%>"></div>
        </div>

        <script type="text/javascript">
          children("<%=card.id%>")
        </script>
      <%end%>

app/views/cards/_card_report.html.erb
  	<p><b><%= @board.title %></b></p>
  	<p>  <%= link_to 'New Card', new_board_card_path %></p>
    <p>  <%= link_to 'Back To Boards', boards_path %></p>
    <table class="table table-bordered" >
      <tr>
        <th>
          Completed Cards
        </th>
      </tr>
      <% @completed_cards.each do |card| %>
      <tr>
        <td><%=card.title%></td>
      </tr>
      <% end %>
    </table>

    <table class="table table-bordered">
      <tr>
        <th>
          Incompleted Cards
        </th>
      </tr>
      <% @uncompleted_cards.each do |card| %>
      <tr>
        <td><%=card.title%></td>
      </tr>
      <% end %>
    </table>    

app/views/cards/_form.html.erb
<%= form_for [@board, @card] do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, :class => "form-control" %>
</div>

<div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, :class => "form-control" %>
</div>

<div class="form-group">
    <%= form.label :parent %>
    <%= form.select :parent_id , options_for_select(@cards), :class => 'form-control', :prompt => 'Select any one' %>
</div>

  <div class="form-group">
    <%= form.submit "Create",  :class => 'btn btn-info' %>
  </div>
<% end %>

app/views/cards/create.html.erb
<h1>Cards#create</h1>
<p>Find me in app/views/cards/create.html.erb</p>

app/views/cards/edit.html.erb
<h1>Cards#edit</h1>
<p>Find me in app/views/cards/edit.html.erb</p>

app/views/cards/get_children.js.erb
$("#parent_<%= @parent.id %>").html("<%= escape_javascript(render('card')) %>")

app/views/cards/index.html.erb
<div class="container-fluid text-center">    
<p id="notice"><%= notice %></p>
  <div class="row content">
  	<div class="col-sm-3 canvas-col" id="card_report">
      <%= render 'card_report' %>

  	</div>
  	<div class="col-sm-9 canvas-col" style="background: #f1f1f1;">
  		<% @cards.each do |card| %>
  			<div class="row" style="margin-bottom: 5px;">

  			<div class="col-sm-2 card-1" style="border-color: <%=border_color(card)%>" onclick="card_tasks('<%=card.id%>')" id="card_<%=card.id%>" >
  				<%=card.title%>	 
  			</div>

			  <!-- Modal -->
			  <div class="tasks_modal" id="Modal_<%=card.id%>" >
			  </div>

  			<div class="col" id="parent_<%=card.id%>"></div>
  			</div>

  			<script type="text/javascript">
  				children("<%=card.id%>")
  			</script>
  		<%end%>

  	</div>
  </div>
</div>

app/views/cards/new.html.erb
<div class="container">

<h1>New Card</h1>

	<%= render 'form', card: @card %>
	<div class="form-group">
	<%= link_to 'Back', board_cards_path %>
	</div>
</div>

app/views/cards/show.html.erb
<div class="container-fluid text-center">
<br><br>
	<div class="col-11">
		<%= link_to 'Back To Cards' , board_cards_path(@board) %>
		<table class="table table-bordered">
			<tbody>
				<tr>
					<th>Title</th>
					<td><%= @card.title %></td>
				</tr>
				<tr>
					<th>Description</th>
					<td><%= @card.description %> </td>
				</tr>
				<tr>
					<th>Parent Card</th>
					<td>

						<%= @card.parent_id.blank? ? 'No' : link_to(@card.parent.try(:title),@card.parent_id)  %>
					</td>
				</tr>
			</tbody>
		</table>

			<ul class="list-group">
					  
			<li class="list-group-item">
				<b>Tasks</b>
			 </li>
			<% @tasks.each do |task| %>
			      <li class="list-group-item ">
			       <span style="color: <%= task.completed ? "red" : "green" %>;"><%=task.title%></span>
			        
			     </li>
			 <%end%>			 
			</ul>

	</div>
</div>

app/views/cards/update.html.erb
<h1>Cards#update</h1>
<p>Find me in app/views/cards/update.html.erb</p>